name: quantecon
channels:
  - default
dependencies:
  - python=3.8
  - anaconda=2021.05
  - pip
  - pip:
    - jupyter-book
    - quantecon-book-theme
    - sphinx-tojupyter
    - sphinxext-rediraffe
    - sphinx-exercise
    - ghp-import
    - sphinxcontrib-youtube


