name: quantecon
channels:
  - default
dependencies:
  - python=3.9
  - anaconda=2021.11
  - pip
  - pip:
    - jupyter-book
    - quantecon-book-theme
    - sphinx-tojupyter
    - sphinxext-rediraffe
    - sphinx-exercise
    - ghp-import
    - sphinxcontrib-youtube
    - quantecon
    - array-to-latex
    - PuLP
    - cvxpy
    - cvxopt
    - cylp
    - prettytable


