title: Python Sandpit
author: Thomas J. Sargent
logo: _static/qe-logo-large.png

parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution

execute:
  execute_notebooks: "cache"
  timeout: 3600
  run_in_temp: true

sphinx:
  # extra_extensions: [sphinx_multitoc_numbering]
  config:
    html_logo: _static/qe-logo.png
    html_favicon: _static/qe-logo.png
    html_theme: quantecon_book_theme
    html_static_path: ['_static']
    html_theme_options:
      header_organisation_url: https://quantecon.org
      header_organisation: QuantEcon
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  
bibtex_bibfiles:
    - _static/quant-econ.bib