title: Python Sandpit
author: Thomas J. Sargent
logo: _static/qe-logo-large.png

parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution

execute:
  execute_notebooks: "cache"
  timeout: 3600
  # run_in_temp: true

sphinx:
  extra_extensions: [sphinxcontrib.youtube, sphinx.ext.todo]
  config:
    html_logo: _static/qe-logo.png
    html_favicon: _static/qe-logo.png
    html_theme: quantecon_book_theme
    html_static_path: ['_static']
    html_theme_options:
      header_organisation_url: https://quantecon.org
      header_organisation: QuantEcon
    # mathjax_config:
    #   TeX:
    #     extensions: ["autobold.js"]
    #     Macros:
    #       "argmax" : "arg\\,max"
    #       "argmin" : "arg\\,min"
    #       "col"    : "col"
    #     tex2jax: 
    #       inlineMath: [ ['$','$'], ['\\(','\\)'] ]
    #       processEscapes: true
    #     SVG:
    #       scale: 0.92,
    #       useGlobalCache: true
    # mathjax_path: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_SVG.js
  
bibtex_bibfiles:
  - _static/quant-econ.bib
  - _static/quant-econ-tom.bib